name: Build With CMake
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3

     - name: Configure
       run: cmake -DQtTemplate_BUILD_TEST=ON -DQtTemplate_AUTO_RUN_TEST=ON .

     - name: Build
       run: make
